server_name: Aidans PC
device_id: 2306
iface: wlp0s20f3
port: 47808

ai_max: 10
ao_max: 10
av_max: 10
bi_max: 10
bo_max: 10
bv_max: 10


bacnet_client:
    commands:
        - whois
        - read_value
        - write_value
        - pics
    debug: false
    enable: true
    tokens:
        - txn_source
        - txn_number

mqtt:
    broker_ip: 127.0.0.1
    broker_port: 1883
    debug: true
    enable: true
    retry_enable: true
    retry_interval: 10
    retry_limit: 5
    write_via_subscribe: true

objects:
    - ai
    - av
    - ao
    - bi
    - bo
    - bv

properties:
    - name
    - pv
    - pri
